USE [master]
GO

/****** Object:  Database [BANCARIO]    Script Date: 6/8/2022 10:27:59 a. m. ******/
CREATE DATABASE [BANCARIO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BANCARIO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BANCARIO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BANCARIO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BANCARIO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BANCARIO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BANCARIO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BANCARIO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BANCARIO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BANCARIO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BANCARIO] SET ARITHABORT OFF 
GO

ALTER DATABASE [BANCARIO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BANCARIO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BANCARIO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BANCARIO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BANCARIO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BANCARIO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BANCARIO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BANCARIO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BANCARIO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BANCARIO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BANCARIO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BANCARIO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BANCARIO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BANCARIO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BANCARIO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BANCARIO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BANCARIO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BANCARIO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BANCARIO] SET  MULTI_USER 
GO

ALTER DATABASE [BANCARIO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BANCARIO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BANCARIO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BANCARIO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BANCARIO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BANCARIO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BANCARIO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BANCARIO] SET  READ_WRITE 
GO

