//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.REGISTRARE1 = new HashSet<REGISTRARE>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string FOTO { get; set; }
        public Nullable<int> IDREGISTRAR { get; set; }
        public string CORREO { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual REGISTRARE REGISTRARE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRARE> REGISTRARE1 { get; set; }
    }
}
