

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DATA
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;
    using ENTITY;

    public partial class BANCARIOEntities : DbContext
{
    public BANCARIOEntities()
        : base("name=BANCARIOEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AHORRO> AHORRO { get; set; }

    public virtual DbSet<CLIENTE> CLIENTE { get; set; }

    public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }

    public virtual DbSet<ESTATUS> ESTATUS { get; set; }

    public virtual DbSet<PRESTAMO> PRESTAMO { get; set; }

    public virtual DbSet<REGISTRARC> REGISTRARC { get; set; }

    public virtual DbSet<REGISTRARE> REGISTRARE { get; set; }

    public virtual DbSet<TARJETA> TARJETA { get; set; }


    public virtual int SP_DEPOSITOS(Nullable<int> monto, Nullable<int> idahorro, Nullable<int> idahorro2)
    {

        var montoParameter = monto.HasValue ?
            new ObjectParameter("monto", monto) :
            new ObjectParameter("monto", typeof(int));


        var idahorroParameter = idahorro.HasValue ?
            new ObjectParameter("idahorro", idahorro) :
            new ObjectParameter("idahorro", typeof(int));


        var idahorro2Parameter = idahorro2.HasValue ?
            new ObjectParameter("idahorro2", idahorro2) :
            new ObjectParameter("idahorro2", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DEPOSITOS", montoParameter, idahorroParameter, idahorro2Parameter);
    }


    public virtual int SP_AVANCE(Nullable<int> monto, Nullable<int> idahorro, Nullable<int> idtarjeta)
    {

        var montoParameter = monto.HasValue ?
            new ObjectParameter("monto", monto) :
            new ObjectParameter("monto", typeof(int));


        var idahorroParameter = idahorro.HasValue ?
            new ObjectParameter("idahorro", idahorro) :
            new ObjectParameter("idahorro", typeof(int));


        var idtarjetaParameter = idtarjeta.HasValue ?
            new ObjectParameter("idtarjeta", idtarjeta) :
            new ObjectParameter("idtarjeta", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AVANCE", montoParameter, idahorroParameter, idtarjetaParameter);
    }


    public virtual int SP_PAGOPRESTAMO(Nullable<int> monto, Nullable<int> idahorro, Nullable<int> idprestamo)
    {

        var montoParameter = monto.HasValue ?
            new ObjectParameter("monto", monto) :
            new ObjectParameter("monto", typeof(int));


        var idahorroParameter = idahorro.HasValue ?
            new ObjectParameter("idahorro", idahorro) :
            new ObjectParameter("idahorro", typeof(int));


        var idprestamoParameter = idprestamo.HasValue ?
            new ObjectParameter("idprestamo", idprestamo) :
            new ObjectParameter("idprestamo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PAGOPRESTAMO", montoParameter, idahorroParameter, idprestamoParameter);
    }


    public virtual int SP_PAGOTARJETA(Nullable<int> monto, Nullable<int> idahorro, Nullable<int> idtarjeta)
    {

        var montoParameter = monto.HasValue ?
            new ObjectParameter("monto", monto) :
            new ObjectParameter("monto", typeof(int));


        var idahorroParameter = idahorro.HasValue ?
            new ObjectParameter("idahorro", idahorro) :
            new ObjectParameter("idahorro", typeof(int));


        var idtarjetaParameter = idtarjeta.HasValue ?
            new ObjectParameter("idtarjeta", idtarjeta) :
            new ObjectParameter("idtarjeta", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PAGOTARJETA", montoParameter, idahorroParameter, idtarjetaParameter);
    }

}

}

